[project]
name = "roux"
version = "0.1.4"

## docs
readme = "README.md"
description = "Convenience functions."
authors = [
  { name = "rraadd88", email = "rohanadandage@gmail.com" }
]
urls = { "Homepage" = "http://github.com/rraadd88/roux" }
classifiers = [
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
]
license = "GPL-3.0-or-later"

## requires
requires-python = ">=3.10, <4"
dependencies = [
    "numpy>=1.17.3",
    "pandas>=0.25.3,<=2.3.3",
    "pyyaml>=5.1",
    "matplotlib>=2.2",
    "seaborn>=0.8",
    "tqdm>=4.38.0", # logging
    # "regex>=2018.7.11",
]

## optional dependencies, installed as extras e.g. `uv add "roux[all]"`
[project.optional-dependencies]
data = [
    "pyarrow", # fast
    "openpyxl", # special io
    "numexpr", # faster querying
    "chardet", # encoding detection
]
stat = [
    "scipy>=1.1.0",
    "statsmodels>=0.13.5",
    "networkx",
    "scikit-learn",
    "pingouin>=0.5.5",
    "patsy",
    "kneed",
]
viz = [
    "altair",
    "adjustText",
    "matplotlib-venn",
    "upsetplot",
    "plotly",
]
fast = [
    "pandarallel",
    "joblib",
]
workflow = [
    "omegaconf",
    "papermill",
    "argh",
    "ruff",
    "nbconvert",
    "nbformat",
    "removestar",
    "gitpython",
]
all = [
    "roux[data,stat,viz,fast,workflow]",
]

## development and maintenance (not published)
[dependency-groups]
dev = [
    "pytest",
    "pytest-cov >= 2,< 7",
    "coveralls == 3.*",
    "tox",
    "tox-uv",
    "tox-gh-actions",
    "jupyter","ipywidgets","ipykernel",
    # "sphinx","recommonmark",
    "black",
    "flake8",
    "isort",
    "papermill",
    "lazydocs",
    "regex", ## docs
]

[tool.uv]
package = true

[tool.setuptools.packages.find]
include = ["roux*"]

[tool.black]
experimental-string-processing = true
line-length = 120
skip-string-normalization = true

[tool.isort]
profile = "black"

[project.scripts]
roux = "roux.run:parser.dispatch"

[build-system]
requires = ["setuptools>=77"] # for SPDX license string
build-backend = "setuptools.build_meta"
