[tox]
envlist = py310, py311, py312

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
passenv = *
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
package = editable
extras = all
dependency_groups = dev
commands_pre =
    python -m ipykernel install --user --name=python3
commands = pytest -vv --maxfail=3 -W always {posargs}