name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonversion: ["3.7", "3.8", "3.9"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pythonversion }}
      # - name: Install Dependencies
      #   run: pip install 
      # - name: Run tests
      #   run: make coverage
#       - name: Coveralls
#         if: github.ref == 'refs/heads/master'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: venv/bin/coveralls --service=github
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[base,interactive,data,stat,viz,workflow,dev]"
          pip install tox-gh-actions
      - name: Run the tests
        run: tox
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
        # with:
        #   file: ./coverage.xml
        #   flags: unittests
        #   name: codecov-umbrella
        #   fail_ci_if_error: false