name: build

on:
  push:
    branches: [ '**' ]      # triggers on all branches
    paths:
      - "roux/**"           # triggers on any file change in roux/ or its subfolders
  pull_request:
    branches: [ '**' ]      # triggers on all branches
    paths:
      - "roux/**"           # triggers on any file change in roux/ or its subfolders

jobs:
  build-n-test-n-coverage:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
            # - "3.8"
            # - "3.9"
            - "3.10"
            - "3.11"
            - "3.12"
    env:
      OS: ubuntu-latest
      PYTHON: "3.12.8"
                
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
          uv pip install -e ".[all]"
      
      - name: Ensure tox
        run: uv pip install tox pytest pytest-cov testbook
      
      - name: Verify installed packages
        run: uv pip list
        
      - name: Run the tests
        run: uv run tox
